name: 🚀 Deploy CI4 to FTP Hosting

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy via FTP (Dry Run)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: sidang-skripsi.my.id
          username: remote@sidang-skripsi.my.id
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/ptpn4.sidang-skripsi.my.id/public_html/internship/
          local-dir: ./
          dry-run: true
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/tests/**
            **/.env

            
